import { z } from "zod";

import { createTRPCRouter, publicProcedure } from "@/server/api/trpc";

export const messageRouter = createTRPCRouter({
  /**
   * Fetches all messages in chronological order
   * TODO: Add pagination for better performance with large message counts
   */
  getAll: publicProcedure.query(async ({ ctx }) => {
    const messages = await ctx.db.message.findMany({
      orderBy: { createdAt: "asc" }, // Oldest first for chat-like experience
    });

    return messages;
  }),

  /**
   * Creates a new message with validation
   * Validates content length, username, and color format
   */
  create: publicProcedure
    .input(
      z.object({
        content: z.string().min(1).max(500), // Message content limits
        username: z.string().min(1).max(50), // Username length limits
        color: z.string().regex(/^#[0-9A-Fa-f]{6}$/), // Hex color validation
      })
    )
    .mutation(async ({ ctx, input }) => {
      return ctx.db.message.create({
        data: {
          content: input.content,
          username: input.username,
          color: input.color,
          // createdAt is auto-generated by Prisma
        },
      });
    }),
});